version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/app/scripts
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu

artifacts:
  files:
    - appspec.yml
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ubuntu
 
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ubuntu
