version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop_unix.sh
      timeout: 1000
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_unix.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_unix.sh
      timeout: 600
      runas: ubuntu
