version: 0.0
os: linux

files:
  - source: scripts
    destination: /home/ubuntu/app
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu
hooks:
  ApplicationStop:
    - location: /home/ubuntu/app/stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/app/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/app/start.sh
      timeout: 600
      runas: ubuntu
